// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: domains.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name, provider, status, created_at, expires_at)
VALUES ($1, $2, $3, NOW(), $4)
RETURNING id, name, provider, status, created_at, expires_at, is_deleted, settings
`

type CreateDomainParams struct {
	Name      string       `json:"name"`
	Provider  string       `json:"provider"`
	Status    int32        `json:"status"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.Name,
		arg.Provider,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsDeleted,
		&i.Settings,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT d.id, d.name, d.provider, d.status, d.created_at, d.expires_at, d.is_deleted, d.settings,
       COUNT(m.id) FILTER (WHERE m.is_deleted = false) as mailbox_count
FROM domains d
LEFT JOIN mailboxes m ON d.id = m.domain_id
WHERE d.is_deleted = false
GROUP BY d.id
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllDomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAllDomainsRow struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	Provider     string                `json:"provider"`
	Status       int32                 `json:"status"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	IsDeleted    sql.NullBool          `json:"is_deleted"`
	Settings     pqtype.NullRawMessage `json:"settings"`
	MailboxCount int64                 `json:"mailbox_count"`
}

func (q *Queries) GetAllDomains(ctx context.Context, arg GetAllDomainsParams) ([]GetAllDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllDomainsRow{}
	for rows.Next() {
		var i GetAllDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsDeleted,
			&i.Settings,
			&i.MailboxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, name, provider, status, created_at, expires_at, is_deleted, settings FROM domains
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDomainByID(ctx context.Context, id int32) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsDeleted,
		&i.Settings,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, name, provider, status, created_at, expires_at, is_deleted
FROM domains
WHERE name = $1
`

type GetDomainByNameRow struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Provider  string       `json:"provider"`
	Status    int32        `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	IsDeleted sql.NullBool `json:"is_deleted"`
}

func (q *Queries) GetDomainByName(ctx context.Context, name string) (GetDomainByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainByName, name)
	var i GetDomainByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDomainsCount = `-- name: GetDomainsCount :one
SELECT COUNT(*) FROM domains
`

func (q *Queries) GetDomainsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDomainsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setDomainStatus = `-- name: SetDomainStatus :exec
UPDATE domains 
SET status = $2
WHERE id = $1
`

type SetDomainStatusParams struct {
	ID     int32 `json:"id"`
	Status int32 `json:"status"`
}

func (q *Queries) SetDomainStatus(ctx context.Context, arg SetDomainStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDomainStatus, arg.ID, arg.Status)
	return err
}

const updateDomain = `-- name: UpdateDomain :exec
UPDATE domains 
SET name = $2, provider = $3
WHERE id = $1
`

type UpdateDomainParams struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Provider string `json:"provider"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) error {
	_, err := q.db.ExecContext(ctx, updateDomain, arg.ID, arg.Name, arg.Provider)
	return err
}
