// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: domains.sql

package db

import (
	"context"
	"database/sql"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name, provider, status, created_at, expires_at)
VALUES ($1, $2, $3, NOW(), $4)
RETURNING id
`

type CreateDomainParams struct {
	Name      string        `json:"name"`
	Provider  string        `json:"provider"`
	Status    sql.NullInt32 `json:"status"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.Name,
		arg.Provider,
		arg.Status,
		arg.ExpiresAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const getAllDomains = `-- name: GetAllDomains :many
SELECT id, name, provider, status, created_at, expires_at
FROM domains
ORDER BY created_at DESC
`

type GetAllDomainsRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Provider  string        `json:"provider"`
	Status    sql.NullInt32 `json:"status"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
}

func (q *Queries) GetAllDomains(ctx context.Context) ([]GetAllDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllDomainsRow{}
	for rows.Next() {
		var i GetAllDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, name, provider, status, created_at, expires_at
FROM domains
WHERE name = $1
`

type GetDomainByNameRow struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Provider  string        `json:"provider"`
	Status    sql.NullInt32 `json:"status"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
}

func (q *Queries) GetDomainByName(ctx context.Context, name string) (GetDomainByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainByName, name)
	var i GetDomainByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setDomainStatus = `-- name: SetDomainStatus :exec
UPDATE domains
SET status = $1
WHERE id = $2
`

type SetDomainStatusParams struct {
	Status sql.NullInt32 `json:"status"`
	ID     int32         `json:"id"`
}

func (q *Queries) SetDomainStatus(ctx context.Context, arg SetDomainStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDomainStatus, arg.Status, arg.ID)
	return err
}
