// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Domain struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	Provider  string        `json:"provider"`
	Status    sql.NullInt32 `json:"status"`
	CreatedAt sql.NullTime  `json:"created_at"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	IsDeleted interface{}   `json:"is_deleted"`
}

type Mailbox struct {
	ID        int32         `json:"id"`
	Address   string        `json:"address"`
	Password  string        `json:"password"`
	DomainID  sql.NullInt32 `json:"domain_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	Status    sql.NullInt32 `json:"status"`
	IsDeleted interface{}   `json:"is_deleted"`
}
