// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"fixed inset-y-0 left-0 z-50 w-64 bg-white shadow-lg\"><div class=\"flex h-16 items-center justify-between px-6 border-b border-gray-200\"><span class=\"text-xl font-bold text-gray-900\">DM</span> <button type=\"button\" class=\"p-1.5\"><i class=\"fa-solid fa-circle-user text-gray-400 hover:text-indigo-600 text-xl transition-colors\"></i></button></div><nav class=\"px-4 py-4\"><div class=\"space-y-1\"><a href=\"/domains\" class=\"flex items-center px-4 py-3 text-sm font-medium rounded-md hover:bg-gray-50 transition-colors\"><i class=\"fa-solid fa-globe text-indigo-600 text-lg w-6\"></i> <span class=\"ml-3 text-gray-900\">Domains</span></a> <a href=\"/mailboxes\" class=\"flex items-center px-4 py-3 text-sm font-medium rounded-md hover:bg-gray-50 transition-colors\"><i class=\"fa-solid fa-envelope text-indigo-600 text-lg w-6\"></i> <span class=\"ml-3 text-gray-900\">Mailboxes</span></a><div class=\"border-t border-gray-200 my-4\"></div><a href=\"/settings\" class=\"flex items-center px-4 py-3 text-sm font-medium rounded-md hover:bg-gray-50 transition-colors\"><i class=\"fa-solid fa-gear text-indigo-600 text-lg w-6\"></i> <span class=\"ml-3 text-gray-900\">Settings</span></a></div></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
